"""Domain-neutral primitives for finite partial-information decision systems.

The core package intentionally contains no Pokémon, Showdown, or poke-env semantics.
Domain adapters may depend on this package; the core package must not depend on them.
"""

from azelficoast.core.contracts import (
    BeliefEvaluator,
    PartialInformationDomain,
    TransitionOracleProducer,
)
from azelficoast.core.costing import (
    CacheRouteEstimate,
    CacheTierCost,
    ExecutionCostProfile,
    ExecutionDecision,
    ExecutionFeatures,
    ExecutionPath,
    LocalityEvidence,
    choose_execution_path,
    estimate_cache_route,
)
from azelficoast.core.decision_relevance import (
    CERTIFICATE_SCHEMA,
    CERTIFICATE_SCHEMA_VERSION,
    DecisionRelevanceError,
    decision_relevance_quotient,
)
from azelficoast.core.program import (
    EXECUTION_SCHEMA,
    EXECUTION_SCHEMA_VERSION,
    PROGRAM_SET_SCHEMA,
    PROGRAM_SET_SCHEMA_VERSION,
    VERIFICATION_SCHEMA,
    VERIFICATION_SCHEMA_VERSION,
    TransitionProgramError,
    program_for_action,
)
from azelficoast.core.memo import MemoKey, MemoStats, SemanticMemo
from azelficoast.core.planning import (
    DEFAULT_DECISION_PLAN,
    OPERATOR_PLAN_EXPLAIN_SCHEMA,
    OPERATOR_PLAN_EXPLAIN_SCHEMA_VERSION,
    PLAN_EXPLAIN_SCHEMA,
    PLAN_EXPLAIN_SCHEMA_VERSION,
    LogicalOperator,
    LogicalPlan,
    OperatorImplementation,
    OperatorPhysicalPlan,
    PhysicalPlan,
    choose_operator_implementation,
    choose_physical_plan,
    explain_operator_plan,
    explain_physical_plan,
)
from azelficoast.core.statistics import (
    CardinalityEstimate,
    CardinalityHistogram,
    CategoricalDependency,
    PlannerStatistics,
    analyze_categorical_dependency,
)
from azelficoast.core.search import (
    SEARCH_METHODS,
    SEARCH_SCHEMA,
    SEARCH_SCHEMA_VERSION,
    PartialInformationSearchError,
    search_transition_program,
)
from azelficoast.core.sql import (
    DECISION_QUERY_SEMANTIC_ID,
    DECISION_QUERY_SEMANTIC_SCHEMA,
    DECISION_QUERY_SEMANTIC_VERSION,
    DECISION_SQL_SURFACE_ID,
    DECISION_SQL_SURFACE_SCHEMA,
    DECISION_SQL_SURFACE_VERSION,
    DEFAULT_DECISION_SQL,
    SQL_EXPLAIN_SCHEMA,
    SQL_EXPLAIN_SCHEMA_VERSION,
    PreparedDecisionQuery,
    SQLDecisionQueryError,
    describe_decision_sql_surface,
    explain_decision_query,
    prepare_decision_query,
)
from azelficoast.core.transition import (
    ORACLE_SCHEMA,
    ORACLE_SCHEMA_VERSION,
    canonical_json,
    sha256_json,
    transition_outcomes,
    validate_transition_oracle,
)

__all__ = [
    "CacheRouteEstimate",
    "CacheTierCost",
    "CardinalityEstimate",
    "CardinalityHistogram",
    "CategoricalDependency",
    "DECISION_QUERY_SEMANTIC_ID",
    "DECISION_QUERY_SEMANTIC_SCHEMA",
    "DECISION_QUERY_SEMANTIC_VERSION",
    "DECISION_SQL_SURFACE_ID",
    "DECISION_SQL_SURFACE_SCHEMA",
    "DECISION_SQL_SURFACE_VERSION",
    "DEFAULT_DECISION_PLAN",
    "DEFAULT_DECISION_SQL",
    "ExecutionCostProfile",
    "ExecutionDecision",
    "ExecutionFeatures",
    "ExecutionPath",
    "LocalityEvidence",
    "LogicalOperator",
    "OPERATOR_PLAN_EXPLAIN_SCHEMA",
    "OPERATOR_PLAN_EXPLAIN_SCHEMA_VERSION",
    "MemoKey",
    "MemoStats",
    "LogicalPlan",
    "OperatorImplementation",
    "OperatorPhysicalPlan",
    "PLAN_EXPLAIN_SCHEMA",
    "PLAN_EXPLAIN_SCHEMA_VERSION",
    "PhysicalPlan",
    "PlannerStatistics",
    "PreparedDecisionQuery",
    "BeliefEvaluator",
    "CERTIFICATE_SCHEMA",
    "CERTIFICATE_SCHEMA_VERSION",
    "DecisionRelevanceError",
    "EXECUTION_SCHEMA",
    "EXECUTION_SCHEMA_VERSION",
    "ORACLE_SCHEMA",
    "ORACLE_SCHEMA_VERSION",
    "PROGRAM_SET_SCHEMA",
    "PROGRAM_SET_SCHEMA_VERSION",
    "PartialInformationDomain",
    "PartialInformationSearchError",
    "SEARCH_METHODS",
    "SEARCH_SCHEMA",
    "SEARCH_SCHEMA_VERSION",
    "SQLDecisionQueryError",
    "SQL_EXPLAIN_SCHEMA",
    "SQL_EXPLAIN_SCHEMA_VERSION",
    "SemanticMemo",
    "TransitionOracleProducer",
    "TransitionProgramError",
    "VERIFICATION_SCHEMA",
    "VERIFICATION_SCHEMA_VERSION",
    "analyze_categorical_dependency",
    "canonical_json",
    "choose_execution_path",
    "choose_operator_implementation",
    "choose_physical_plan",
    "decision_relevance_quotient",
    "describe_decision_sql_surface",
    "estimate_cache_route",
    "explain_operator_plan",
    "explain_decision_query",
    "explain_physical_plan",
    "prepare_decision_query",
    "program_for_action",
    "search_transition_program",
    "sha256_json",
    "transition_outcomes",
    "validate_transition_oracle",
]
